USE master;

DROP DATABASE IF EXISTS timesheet_db;
CREATE DATABASE timesheet_db;

USE timesheet_db;

DELETE FROM timesheet.COUNTRY;
DELETE FROM timesheet.CLIENT;
DELETE FROM timesheet.PROJECT;
DELETE FROM timesheet.TASK_TABLE
DELETE FROM timesheet.LEAD_PROJECT
DELETE FROM timesheet.USER_PROJECT

SELECT * FROM dbo.__EFMigrationsHistory;
SELECT * FROM timesheet.COUNTRY;
SELECT * FROM timesheet.USER_TABLE;

SELECT* FROM timesheet.CLIENT cl WHERE cl.CLIENT_ADDRESS = 'Street 14';

SELECT * FROM timesheet.CLIENT cl
INNER JOIN timesheet.COUNTRY co ON (cl.COUNTRY_ID = co.ID)
WHERE co.COUNTRY_NAME = 'Norway';

ALTER TABLE timesheet.USER_TABLE ALTER COLUMN ROLE_ID UNIQUEIDENTIFIER NULL
	

DROP TABLE IF EXISTS timesheet.LEAD_PROJECT;
DROP TABLE IF EXISTS timesheet.TASK_TABLE;
DROP TABLE IF EXISTS timesheet.USER_PROJECT;
DROP TABLE IF EXISTS timesheet.PROJECT;
DROP TABLE IF EXISTS timesheet.CLIENT;
DROP TABLE IF EXISTS timesheet.COUNTRY;
DROP TABLE IF EXISTS timesheet.USER_TABLE;
DROP TABLE IF EXISTS timesheet.ROLE_TABLE;
DROP TABLE IF EXISTS timesheet.CATEGORY;

GO
IF SCHEMA_ID('timesheet') IS NOT NULL
	DROP SCHEMA timesheet;
GO
CREATE SCHEMA timesheet;
GO

CREATE TABLE timesheet.ROLE_TABLE (
	ID UNIQUEIDENTIFIER PRIMARY KEY,
	ROLE_NAME VARCHAR(50) NOT NULL,
	DELETED_DATE DATETIME
);

CREATE TABLE timesheet.USER_TABLE (
	ID UNIQUEIDENTIFIER PRIMARY KEY,
	ROLE_ID UNIQUEIDENTIFIER,
	EMAIL VARCHAR(50) NOT NULL,
	USERNAME VARCHAR(50) NOT NULL,
	USER_PASSWORD VARCHAR(50) NOT NULL,
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NOT NULL,
	HOURS_PER_WEEK INT NOT NULL,
	USER_STATUS VARCHAR(20) NOT NULL,
	DELETED_DATE DATETIME,
	CONSTRAINT FK_USER_ROLE FOREIGN KEY (ROLE_ID) REFERENCES timesheet.ROLE_TABLE(ID)
);

CREATE TABLE timesheet.COUNTRY (
	ID UNIQUEIDENTIFIER PRIMARY KEY,
	COUNTRY_NAME VARCHAR(50) NOT NULL,
	DELETED_DATE DATETIME
);

CREATE TABLE timesheet.CLIENT (
	ID UNIQUEIDENTIFIER PRIMARY KEY,
	COUNTRY_ID UNIQUEIDENTIFIER,
	CLIENT_NAME VARCHAR(50) NOT NULL,
	CLIENT_ADDRESS VARCHAR(50),
	CLIENT_CITY VARCHAR(50),
	CLIENT_ZIP_CODE VARCHAR(20),
	CONSTRAINT FK_CLIENT_COUNTRY FOREIGN KEY (COUNTRY_ID) REFERENCES timesheet.COUNTRY(ID)
);

CREATE TABLE timesheet.PROJECT (
	ID UNIQUEIDENTIFIER PRIMARY KEY,
	CLIENT_ID UNIQUEIDENTIFIER NOT NULL,
	PROJECT_NAME VARCHAR(50) NOT NULL,
	PROJECT_DESCRIPTION VARCHAR(200),
	PROJECT_STATUS VARCHAR(20) NOT NULL,
	DELETED_DATE DATETIME,
	CONSTRAINT FK_PROJECT_CLIENT FOREIGN KEY (CLIENT_ID) REFERENCES timesheet.CLIENT(ID)
);

CREATE TABLE timesheet.USER_PROJECT (
	USER_TABLE_ID UNIQUEIDENTIFIER NOT NULL,
	PROJECT_ID UNIQUEIDENTIFIER NOT NULL,
	DELETED_DATE DATETIME,
	CONSTRAINT PK_USER_PROJECT PRIMARY KEY (USER_TABLE_ID, PROJECT_ID),
	CONSTRAINT FK_USER_PROJECT_USER_TABLE FOREIGN KEY (USER_TABLE_ID) REFERENCES timesheet.USER_TABLE(ID),
	CONSTRAINT FK_USER_PROJECT_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES timesheet.PROJECT(ID),
);

CREATE TABLE timesheet.LEAD_PROJECT (
	USER_TABLE_ID UNIQUEIDENTIFIER NOT NULL,
	PROJECT_ID UNIQUEIDENTIFIER NOT NULL,
	DELETED_DATE DATETIME,
	CONSTRAINT PK_LEAD_PROJECT PRIMARY KEY (USER_TABLE_ID, PROJECT_ID),
	CONSTRAINT FK_LEAD_PROJECT_USER_PROJECT FOREIGN KEY (USER_TABLE_ID, PROJECT_ID) REFERENCES timesheet.USER_PROJECT(USER_TABLE_ID, PROJECT_ID),
);

CREATE TABLE timesheet.CATEGORY (
	ID UNIQUEIDENTIFIER PRIMARY KEY,
	CATEGORY_NAME VARCHAR(50) NOT NULL,
	DELETED_DATE DATETIME
);

CREATE TABLE timesheet.TASK_TABLE (
	ID UNIQUEIDENTIFIER PRIMARY KEY,
	USER_TABLE_ID UNIQUEIDENTIFIER NOT NULL,
	PROJECT_ID UNIQUEIDENTIFIER NOT NULL,
	CATEGORY_ID UNIQUEIDENTIFIER,
	TASK_DESCRIPTION VARCHAR(200),
	TASK_TIME NUMERIC(4, 2) NOT NULL,
	TASK_OVERTIME NUMERIC(4, 2),
	TASK_DATE DATE NOT NULL,
	CONSTRAINT FK_TASK_USER_PROJECT FOREIGN KEY (USER_TABLE_ID, PROJECT_ID) REFERENCES timesheet.USER_PROJECT(USER_TABLE_ID, PROJECT_ID),
	CONSTRAINT FK_TASK_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES timesheet.CATEGORY(ID)
);


INSERT INTO timesheet.COUNTRY (COUNTRY_NAME) VALUES ('Serbia');
INSERT INTO timesheet.COUNTRY (COUNTRY_NAME) VALUES ('Brazil');
INSERT INTO timesheet.COUNTRY (COUNTRY_NAME) VALUES ('Croatia');
INSERT INTO timesheet.COUNTRY (COUNTRY_NAME) VALUES ('Germany');
INSERT INTO timesheet.COUNTRY (COUNTRY_NAME) VALUES ('Hungary');
INSERT INTO timesheet.COUNTRY (COUNTRY_NAME) VALUES ('France');
INSERT INTO timesheet.COUNTRY (COUNTRY_NAME) VALUES ('England');

--SELECT * FROM timesheet.COUNTRY;

INSERT INTO timesheet.CATEGORY (CATEGORY_NAME) VALUES ('Front-end development');
INSERT INTO timesheet.CATEGORY (CATEGORY_NAME) VALUES ('Design');

--SELECT * FROM timesheet.CATEGORY;

INSERT INTO timesheet.ROLE_TABLE (ID, ROLE_NAME) VALUES ('a215d8b1-bd21-4ca5-ad29-54756e20ce79', 'Admin');
INSERT INTO timesheet.ROLE_TABLE (ID, ROLE_NAME) VALUES ('4acf468a-3148-4157-ba63-c6124b385b31','Worker');

--SELECT * FROM timesheet.ROLE_TABLE;

INSERT INTO timesheet.CLIENT (ID, COUNTRY_ID, CLIENT_NAME, CLIENT_ADDRESS, CLIENT_CITY, CLIENT_ZIP_CODE) VALUES ('128f00e9-a7f7-4b99-b7e6-0dafcb93beef','aa221dcc-a592-411d-a5a4-3eac7c8dfb69', 'Petar Petrovic', 'Dositejeva 8', 'Novi Sad', '21000');
INSERT INTO timesheet.CLIENT (COUNTRY_ID, CLIENT_NAME, CLIENT_ADDRESS, CLIENT_CITY, CLIENT_ZIP_CODE) VALUES (2, 'Andrija Andric', 'Brazilska 3', 'Brazilija', '233666');
INSERT INTO timesheet.CLIENT (COUNTRY_ID, CLIENT_NAME, CLIENT_ADDRESS, CLIENT_CITY, CLIENT_ZIP_CODE) VALUES (3, 'Kosta Kostic', 'Zagrebacka 4', 'Zagreb', '555666');
INSERT INTO timesheet.CLIENT (COUNTRY_ID, CLIENT_NAME, CLIENT_ADDRESS, CLIENT_CITY, CLIENT_ZIP_CODE) VALUES (4, 'Ana Anic', 'Minhenska 77', 'Minhen', '123456');
INSERT INTO timesheet.CLIENT (COUNTRY_ID, CLIENT_NAME, CLIENT_ADDRESS, CLIENT_CITY, CLIENT_ZIP_CODE) VALUES (5, 'Marija Maric', 'Petefi Sandora 88', 'Budimpesta', '888999');

SELECT * FROM timesheet.CLIENT cl
INNER JOIN timesheet.COUNTRY co ON (cl.COUNTRY_ID = co.ID)
WHERE cl.CLIENT_NAME = 'Petar Petrovic';

INSERT INTO timesheet.PROJECT (CLIENT_ID, PROJECT_NAME, PROJECT_DESCRIPTION, PROJECT_STATUS) VALUES (1, 'Project1', 'Project Description1', 'Active');
INSERT INTO timesheet.PROJECT (CLIENT_ID, PROJECT_NAME, PROJECT_DESCRIPTION, PROJECT_STATUS) VALUES (1, 'Project2', 'Project Description2', 'Inactive');
INSERT INTO timesheet.PROJECT (CLIENT_ID, PROJECT_NAME, PROJECT_DESCRIPTION, PROJECT_STATUS) VALUES (1, 'Project3', 'Project Description3', 'Active');
INSERT INTO timesheet.PROJECT (CLIENT_ID, PROJECT_NAME, PROJECT_DESCRIPTION, PROJECT_STATUS) VALUES (2, 'Project4', 'Project Description4', 'Inactive');
INSERT INTO timesheet.PROJECT (CLIENT_ID, PROJECT_NAME, PROJECT_DESCRIPTION, PROJECT_STATUS) VALUES (3, 'Project5', 'Project Description5', 'Active');
INSERT INTO timesheet.PROJECT (CLIENT_ID, PROJECT_NAME, PROJECT_DESCRIPTION, PROJECT_STATUS) VALUES (4, 'Project6', 'Project Description6', 'Active');
INSERT INTO timesheet.PROJECT (CLIENT_ID, PROJECT_NAME, PROJECT_DESCRIPTION, PROJECT_STATUS) VALUES (4, 'Project7', 'Project Description7', 'Active');
INSERT INTO timesheet.PROJECT (CLIENT_ID, PROJECT_NAME, PROJECT_DESCRIPTION, PROJECT_STATUS) VALUES (5, 'Project8', 'Project Description8', 'Inactive');

--SELECT * FROM timesheet.PROJECT;

INSERT INTO timesheet.USER_TABLE (ID, ROLE_ID, EMAIL, USER_PASSWORD, FIRST_NAME, LAST_NAME, HOURS_PER_WEEK, USER_STATUS) VALUES ('9744d9ae-7231-42dc-8f41-097cc53281eb','4acf468a-3148-4157-ba63-c6124b385b31', 'sebastijan@gmail.com', 'hesheshes', 'Sebastijan', 'Kokai', 40, 'Active');
INSERT INTO timesheet.USER_TABLE (ROLE_ID, EMAIL, USER_PASSWORD, FIRST_NAME, LAST_NAME, HOURS_PER_WEEK, USER_STATUS) VALUES (2, 'petar@gmail.com', 'hesheshes', 'Petar', 'Mihajlovic', 20, 'Active');
INSERT INTO timesheet.USER_TABLE (ROLE_ID, EMAIL, USER_PASSWORD, FIRST_NAME, LAST_NAME, HOURS_PER_WEEK, USER_STATUS) VALUES (2, 'marijana@gmail.com', 'hesheshes', 'Marijana', 'Lazic', 40, 'Inactive');
INSERT INTO timesheet.USER_TABLE (ROLE_ID, EMAIL, USER_PASSWORD, FIRST_NAME, LAST_NAME, HOURS_PER_WEEK, USER_STATUS) VALUES (1, 'mihajlo@gmail.com', 'hesheshes', 'Mihajlo', 'Blesic', 20, 'Active');
INSERT INTO timesheet.USER_TABLE (ROLE_ID, EMAIL, USER_PASSWORD, FIRST_NAME, LAST_NAME, HOURS_PER_WEEK, USER_STATUS) VALUES (2, 'aleksandar@gmail.com', 'hesheshes', 'Aleksandar', 'Petrovic', 40, 'Active');

SELECT * FROM timesheet.USER_TABLE;

INSERT INTO timesheet.USER_PROJECT (USER_TABLE_ID, PROJECT_ID) VALUES (1, 1);
INSERT INTO timesheet.USER_PROJECT (USER_TABLE_ID, PROJECT_ID) VALUES (1, 2);
INSERT INTO timesheet.USER_PROJECT (USER_TABLE_ID, PROJECT_ID) VALUES (1, 3);
INSERT INTO timesheet.USER_PROJECT (USER_TABLE_ID, PROJECT_ID) VALUES (2, 2);
INSERT INTO timesheet.USER_PROJECT (USER_TABLE_ID, PROJECT_ID) VALUES (2, 3);
INSERT INTO timesheet.USER_PROJECT (USER_TABLE_ID, PROJECT_ID) VALUES (3, 4);
INSERT INTO timesheet.USER_PROJECT (USER_TABLE_ID, PROJECT_ID) VALUES (3, 5);
INSERT INTO timesheet.USER_PROJECT (USER_TABLE_ID, PROJECT_ID) VALUES (4, 1);
INSERT INTO timesheet.USER_PROJECT (USER_TABLE_ID, PROJECT_ID) VALUES (4, 2);
INSERT INTO timesheet.USER_PROJECT (USER_TABLE_ID, PROJECT_ID) VALUES (4, 3);
INSERT INTO timesheet.USER_PROJECT (USER_TABLE_ID, PROJECT_ID) VALUES (5, 4);
INSERT INTO timesheet.USER_PROJECT (USER_TABLE_ID, PROJECT_ID) VALUES (5, 5);

--SELECT * FROM timesheet.USER_PROJECT;

INSERT INTO timesheet.LEAD_PROJECT (USER_TABLE_ID, PROJECT_ID) VALUES (2, 3);
INSERT INTO timesheet.LEAD_PROJECT (USER_TABLE_ID, PROJECT_ID) VALUES (3, 4);
INSERT INTO timesheet.LEAD_PROJECT (USER_TABLE_ID, PROJECT_ID) VALUES (4, 1);

--SELECT * FROM timesheet.LEAD_PROJECT;

INSERT INTO timesheet.TASK_TABLE (USER_TABLE_ID, PROJECT_ID, CATEGORY_ID, TASK_DESCRIPTION, TASK_TIME, TASK_OVERTIME, TASK_DATE) VALUES (1, 1, 1, 'Description of task', 7.5, 1.5, '2021-03-09');
INSERT INTO timesheet.TASK_TABLE (USER_TABLE_ID, PROJECT_ID, CATEGORY_ID, TASK_DESCRIPTION, TASK_TIME, TASK_OVERTIME, TASK_DATE) VALUES (1, 1, 1, 'Description of task', 7.5, 0, '2020-03-09');
INSERT INTO timesheet.TASK_TABLE (USER_TABLE_ID, PROJECT_ID, CATEGORY_ID, TASK_DESCRIPTION, TASK_TIME, TASK_OVERTIME, TASK_DATE) VALUES (1, 2, 1, 'Description of task', 4, 0, '2019-03-09');
INSERT INTO timesheet.TASK_TABLE (USER_TABLE_ID, PROJECT_ID, CATEGORY_ID, TASK_DESCRIPTION, TASK_TIME, TASK_OVERTIME, TASK_DATE) VALUES (1, 3, 1, 'Description of task', 7.5, 0, '2021-04-09');
INSERT INTO timesheet.TASK_TABLE (USER_TABLE_ID, PROJECT_ID, CATEGORY_ID, TASK_DESCRIPTION, TASK_TIME, TASK_OVERTIME, TASK_DATE) VALUES (2, 2, 1, 'Description of task', 7.5, 0, '2021-05-09');
INSERT INTO timesheet.TASK_TABLE (USER_TABLE_ID, PROJECT_ID, CATEGORY_ID, TASK_DESCRIPTION, TASK_TIME, TASK_OVERTIME, TASK_DATE) VALUES (2, 3, 1, 'Description of task', 7.5, 0, '2021-07-09');
INSERT INTO timesheet.TASK_TABLE (USER_TABLE_ID, PROJECT_ID, CATEGORY_ID, TASK_DESCRIPTION, TASK_TIME, TASK_OVERTIME, TASK_DATE) VALUES (3, 4, 1, 'Description of task', 7.5, 0, '2021-09-09');
INSERT INTO timesheet.TASK_TABLE (USER_TABLE_ID, PROJECT_ID, CATEGORY_ID, TASK_DESCRIPTION, TASK_TIME, TASK_OVERTIME, TASK_DATE) VALUES (3, 5, 1, 'Description of task', 4, 0, '2021-03-21');
INSERT INTO timesheet.TASK_TABLE (USER_TABLE_ID, PROJECT_ID, CATEGORY_ID, TASK_DESCRIPTION, TASK_TIME, TASK_OVERTIME, TASK_DATE) VALUES (4, 1, 1, 'Description of task', 7.5, 1.5, '2021-03-23');
INSERT INTO timesheet.TASK_TABLE (USER_TABLE_ID, PROJECT_ID, CATEGORY_ID, TASK_DESCRIPTION, TASK_TIME, TASK_OVERTIME, TASK_DATE) VALUES (5, 4, 1, 'Description of task', 7.5, 3, '2021-04-28');
INSERT INTO timesheet.TASK_TABLE (USER_TABLE_ID, PROJECT_ID, CATEGORY_ID, TASK_DESCRIPTION, TASK_TIME, TASK_OVERTIME, TASK_DATE) VALUES (5, 5, 1, 'Description of task', 7.5, 1, '2021-11-28');
INSERT INTO timesheet.TASK_TABLE (USER_TABLE_ID, PROJECT_ID, CATEGORY_ID, TASK_DESCRIPTION, TASK_TIME, TASK_OVERTIME, TASK_DATE) VALUES (4, 2, 1, 'Description of task', 7.5, 3, '2021-12-28');

SELECT * FROM timesheet.TASK_TABLE;

SELECT * FROM timesheet.COUNTRY;

SELECT * FROM timesheet.USER_TABLE;